### ISSUE TITLE
Build existing code on Blackberry and sign with J2ME cert

### ISSUE THREAD

**Issue by n8fr8** [SaferMobile/InTheClear#2]
for signing java apps on Blackberry, you must use a COD file

**Comment by harlo** [comment]
Ran into a wall trying to build this: I'm getting a permission-denied error that leads me to believe that the JAR is signed?  If this is the case, it fails because RIM's midlet utility does not support signed JARs.  Please advise. (I'll continue to research the problem, in the meanwhile...)

**Comment by harlo** [comment]
hmm.... might i be able to build it from the class files rather than the .jar?

**Comment by eighthave** [comment]
I just committed an ant/bb-ant-tools build system that builds a jar, jad, and cod. It'll do this automatically on the build server.  No signing yet, we need the key on the build server in order to do that.
https://github.com/SaferMobile/InTheClear/commit/327a29f4b3985acc9cd97246b90bd3fed872a581

Here's the setup notes:
https://github.com/SaferMobile/InTheClear/wiki

Here's the build setup:
https://10.0.1.50:8443/job/InTheClear/

**Comment by harlo** [comment]
this is great, HC. would you consult me tomorrow? I hit a wall today and I
think you could help me through it.
On May 24, 2011 6:53 PM, "eighthave" <
reply@reply.github.com>
wrote:

**Comment by n8fr8** [comment]
Yeah, I think you have to build from source again on BB, and not from our JAD and JAR files we produced/signed for other handsets.

**Comment by eighthave** [comment]
The jar/jad/cod built by Jenkins using the Blackberry JDE should work, right?

**Comment by n8fr8** [comment]
We have this working manually for now, which is good enough for me.
