### ISSUE TITLE
FC on test wipe - best result yet, though!

### ISSUE THREAD

**Issue by djhalliday** [SaferMobile/InTheClear#72]
Just tested a full wipe using my existing phone, so lots of contacts, call logs, etc. Results were:
- Contacts, call log, and calendar all wiped! Hooray!
- Pictures remained - at least those labeled as 'Camera' in my Gallery

Ended up eventually getting a force close, and it looks like ITC may have choked on some file or folder in its attempt to wipe the SDCard. Reference relevant portion of logcat here: http://pastebin.com/MwXL0M8W

**Comment by harlo** [comment]
Thanks for this!  This is a good bug to catch!

It's due to the file buffer (that I'm writing zeros to) being too big and
overtaking the memory.  I suppose it means that the file deletion is going
faster than the device's garbage collection.

I handled the error by just the file (and closing any open buffers) and then
prompting garbage collection.

Not 100% sure that that's the perfect fix: I'll do some testing tomorrow.
 If anyone else has suggestions, please let me know!

Thanks,
Harlo

**Comment by harlo** [comment]
Appears to be fixed, but let me know if we encounter this again.
